
#JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

# Configuracion del servidor de correo electronico (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jesiagr@gmail.com
spring.mail.password=pmun fcto gxkl qrib
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL de conexión al Transaction Pooler de Supabase
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0

# Tu usuario único de proyecto
spring.datasource.username=postgres.tnxwgunhhanysemtcvhl

# REEMPLAZA ESTO por tu contraseña real de Supabase
spring.datasource.password=conectarsanjose19

# Driver oficial de PostgreSQL y configuración de Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true